### ISSUE TITLE
IPv4 Link-local implementation doesn't detect IP address collisions

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_network#42] opened 2017-10-10 12:45 UTC
The current IPv4 implementation selects a randomly generated IP address and proceeds to use it without probing for its existence of announcing itself. See https://tools.ietf.org/html/rfc3927#section-2.2.1 for what it should be doing.

**Comment by ConnorRigby** [comment] 2018-03-06 18:38
Closing this issue because it is a duplicate of https://github.com/nerves-project/nerves_network/issues/16

**Closed by ConnorRigby** 2018-03-06 18:38 UTC
Labels: duplicate, enhancement
